[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "[0-9A-Za-z_/]{76}",
    " nd[^a-z_]",
    "from observ import",
    "nothin'",
    "Noto ?Sans ?Vai",
]

[default.extend-words]
"datas" = "datas"

[default.extend-identifiers]
"lod_min_clamp" = "lod_min_clamp"
"lod_max_clamp" = "lod_max_clamp"
